# Generated by Django 5.0.4 on 2024-04-20 17:46

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("maps", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="location",
            name="polygon",
            field=django.contrib.gis.db.models.fields.PolygonField(
                blank=True, null=True, srid=4326, verbose_name="poligono"
            ),
        ),
    ]
