# Generated by Django 5.0.6 on 2024-06-12 09:13

import django.db.models.deletion
import django.db.models.manager
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("maps", "0003_alter_location_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="LocationCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="data di creazione"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, db_index=True, verbose_name="data ultima modifica"
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        unique=True,
                        verbose_name="UUID",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        editable=False,
                        null=True,
                        verbose_name="data di cancellazione",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        db_index=True, max_length=255, unique=True, verbose_name="nome"
                    ),
                ),
                (
                    "icon",
                    models.CharField(blank=True, max_length=255, null=True, verbose_name="icona"),
                ),
            ],
            options={
                "verbose_name": "categoria luogo",
                "verbose_name_plural": "categorie luogo",
            },
            managers=[
                ("objects_with_deleted", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name="location",
            name="is_public",
            field=models.BooleanField(
                default=False,
                help_text="se attivo, viene mostrato sempre sulla mappa",
                verbose_name="pubblico?",
            ),
        ),
        migrations.AddField(
            model_name="location",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="maps.locationcategory",
                verbose_name="categoria",
            ),
        ),
    ]
