# Generated by Django 5.0.6 on 2024-06-13 08:53

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("maps", "0005_location_path_alter_locationcategory_icon"),
    ]

    operations = [
        migrations.AddField(
            model_name="locationcategory",
            name="color",
            field=colorfield.fields.ColorField(
                default="#32a852", image_field=None, max_length=25, samples=None
            ),
        ),
    ]
