# Generated by Django 5.0.6 on 2024-07-08 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("maps", "0006_locationcategory_color"),
    ]

    operations = [
        migrations.AddField(
            model_name="location",
            name="description",
            field=models.TextField(blank=True, null=True, verbose_name="descrizione"),
        ),
    ]
