# Generated by Django 5.1 on 2024-08-17 10:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("maps", "0008_alter_location_coords"),
        ("people", "0037_alter_district_location_alter_subdistrict_location"),
    ]

    operations = [
        migrations.AddField(
            model_name="location",
            name="district",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="district_locations",
                to="people.district",
                verbose_name="sottocampo",
            ),
        ),
    ]
