# Generated by Django 5.0.3 on 2024-03-26 21:37

import django.db.models.deletion
import django.db.models.manager
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("maps", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="data di creazione"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, db_index=True, verbose_name="data ultima modifica"
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        unique=True,
                        verbose_name="UUID",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        editable=False,
                        null=True,
                        verbose_name="data di cancellazione",
                    ),
                ),
                ("name", models.CharField(db_index=True, max_length=255, verbose_name="nome")),
                (
                    "is_registration_required",
                    models.BooleanField(default=True, verbose_name="registrazione richiesta?"),
                ),
                (
                    "registration_limit",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="limite di iscrizioni"
                    ),
                ),
                (
                    "registration_limit_from_same_scout_group",
                    models.PositiveIntegerField(
                        blank=True,
                        null=True,
                        verbose_name="limite di iscrizioni dallo stesso groupo scout",
                    ),
                ),
                ("starts_at", models.DateTimeField(verbose_name="data inizio")),
                ("ends_at", models.DateTimeField(verbose_name="data fine")),
                (
                    "registrations_open_at",
                    models.DateTimeField(verbose_name="data apertura iscrizioni"),
                ),
                (
                    "registrations_close_at",
                    models.DateTimeField(verbose_name="data chiusura iscrizioni"),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("SGUARDI", "SGUARDI"),
                            ("INCONTRI", "INCONTRI"),
                            ("TRACCE", "TRACCE"),
                            ("CONFRONTI", "CONFRONTI"),
                        ],
                        max_length=255,
                        verbose_name="modulo",
                    ),
                ),
                (
                    "location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="maps.location",
                        verbose_name="luogo",
                    ),
                ),
            ],
            options={
                "verbose_name": "evento",
                "verbose_name_plural": "eventi",
            },
            managers=[
                ("objects_with_deleted", django.db.models.manager.Manager()),
            ],
        ),
    ]
