# Generated by Django 5.0.3 on 2024-03-26 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="registrations_close_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="data chiusura iscrizioni"
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="registrations_open_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="data apertura iscrizioni"
            ),
        ),
    ]
