# Generated by Django 5.0.3 on 2024-04-05 21:06

import django.db.models.deletion
import django.db.models.manager
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0002_alter_event_registrations_close_at_and_more"),
        ("people", "0003_alter_person_user_alter_scoutgroup_region"),
    ]

    operations = [
        migrations.CreateModel(
            name="DistrictEventVisibility",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="data di creazione"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, db_index=True, verbose_name="data ultima modifica"
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        unique=True,
                        verbose_name="UUID",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        editable=False,
                        null=True,
                        verbose_name="data di cancellazione",
                    ),
                ),
                (
                    "district",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="people.district",
                        verbose_name="sottocampo",
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="events.event",
                        verbose_name="evento",
                    ),
                ),
            ],
            options={
                "verbose_name": "disponibilità evento a sottocampo",
                "verbose_name_plural": "disponibilità evento a sottocampo",
            },
            managers=[
                ("objects_with_deleted", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name="event",
            name="visibility_to_districts",
            field=models.ManyToManyField(
                through="events.DistrictEventVisibility", to="people.district"
            ),
        ),
        migrations.CreateModel(
            name="PersonEventVisibility",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="data di creazione"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, db_index=True, verbose_name="data ultima modifica"
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        unique=True,
                        verbose_name="UUID",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        editable=False,
                        null=True,
                        verbose_name="data di cancellazione",
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="events.event",
                        verbose_name="evento",
                    ),
                ),
                (
                    "person",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="people.person",
                        verbose_name="persona",
                    ),
                ),
            ],
            options={
                "verbose_name": "disponibilità evento a persona",
                "verbose_name_plural": "disponibilità evento a persona",
            },
            managers=[
                ("objects_with_deleted", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name="event",
            name="visibility_to_persons",
            field=models.ManyToManyField(
                through="events.PersonEventVisibility", to="people.person"
            ),
        ),
        migrations.CreateModel(
            name="ScoutGroupEventVisibility",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="data di creazione"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, db_index=True, verbose_name="data ultima modifica"
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        unique=True,
                        verbose_name="UUID",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        editable=False,
                        null=True,
                        verbose_name="data di cancellazione",
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="events.event",
                        verbose_name="evento",
                    ),
                ),
                (
                    "scout_group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="people.scoutgroup",
                        verbose_name="gruppo scout",
                    ),
                ),
            ],
            options={
                "verbose_name": "disponibilità evento a gruppo scout",
                "verbose_name_plural": "disponibilità evento a gruppo scout",
            },
            managers=[
                ("objects_with_deleted", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name="event",
            name="visibility_to_scout_groups",
            field=models.ManyToManyField(
                through="events.ScoutGroupEventVisibility", to="people.scoutgroup"
            ),
        ),
        migrations.CreateModel(
            name="SquadEventVisibility",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="data di creazione"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, db_index=True, verbose_name="data ultima modifica"
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        unique=True,
                        verbose_name="UUID",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        editable=False,
                        null=True,
                        verbose_name="data di cancellazione",
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="events.event",
                        verbose_name="evento",
                    ),
                ),
                (
                    "squad",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="people.squad",
                        verbose_name="pattuglia",
                    ),
                ),
            ],
            options={
                "verbose_name": "disponibilità evento a pattuglia",
                "verbose_name_plural": "disponibilità evento a pattuglia",
            },
            managers=[
                ("objects_with_deleted", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name="event",
            name="visibility_to_squads",
            field=models.ManyToManyField(through="events.SquadEventVisibility", to="people.squad"),
        ),
        migrations.CreateModel(
            name="SubdistrictEventVisibility",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="data di creazione"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, db_index=True, verbose_name="data ultima modifica"
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        unique=True,
                        verbose_name="UUID",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        editable=False,
                        null=True,
                        verbose_name="data di cancellazione",
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="events.event",
                        verbose_name="evento",
                    ),
                ),
                (
                    "subdistrict",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="people.subdistrict",
                        verbose_name="contrada",
                    ),
                ),
            ],
            options={
                "verbose_name": "disponibilità evento a contrada",
                "verbose_name_plural": "disponibilità evento a contrada",
            },
            managers=[
                ("objects_with_deleted", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name="event",
            name="visibility_to_subdistricts",
            field=models.ManyToManyField(
                through="events.SubdistrictEventVisibility", to="people.subdistrict"
            ),
        ),
    ]
