# Generated by Django 5.0.3 on 2024-04-12 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0004_alter_event_visibility_to_districts_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="is_registration_required",
            field=models.BooleanField(
                default=True, verbose_name="registrazione individuale abilitata?"
            ),
        ),
    ]
