# Generated by Django 5.0.4 on 2024-04-20 17:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cms", "0002_alter_cmspage_options"),
        ("events", "0005_alter_event_is_registration_required"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="page",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="cms.cmspage",
                verbose_name="pagina",
            ),
        ),
    ]
