# Generated by Django 5.0.4 on 2024-04-20 22:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cms", "0003_create_root_pages"),
        ("events", "0006_event_page"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="kind",
            field=models.CharField(
                choices=[
                    ("SGUARDI", "SGUARDI"),
                    ("INCONTRI", "INCONTRI"),
                    ("TRACCE", "TRACCE"),
                    ("CONFRONTI", "CONFRONTI"),
                    ("ALTRO", "ALTRO"),
                ],
                max_length=255,
                verbose_name="modulo",
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="page",
            field=models.ForeignKey(
                blank=True,
                help_text="la pagina CMS viene creata automaticamente al salvataggio dell'evento",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="cms.cmspage",
                verbose_name="pagina",
            ),
        ),
    ]
