# Generated by Django 5.0.6 on 2024-06-05 17:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0011_lineeventvisibility_lineeventregistration"),
        ("people", "0017_remove_scoutgroup_subdistrict_line_scoutgroup_line"),
    ]

    operations = [
        migrations.AddField(
            model_name="lineeventregistration",
            name="line",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="people.line", verbose_name="fila"
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="registered_lines",
            field=models.ManyToManyField(
                related_name="registered_events",
                through="events.LineEventRegistration",
                to="people.line",
            ),
        ),
        migrations.AddField(
            model_name="lineeventvisibility",
            name="event",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="events.event",
                verbose_name="evento",
            ),
        ),
        migrations.AddField(
            model_name="lineeventvisibility",
            name="line",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="people.line", verbose_name="fila"
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="visibility_to_lines",
            field=models.ManyToManyField(
                related_name="visible_events",
                through="events.LineEventVisibility",
                to="people.line",
            ),
        ),
    ]
