# Generated by Django 5.0.6 on 2024-06-14 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0014_event_correlation_id_event_happiness_path"),
    ]

    operations = [
        migrations.AddField(
            model_name="districteventregistration",
            name="check_in",
            field=models.BooleanField(default=False, verbose_name="check-in"),
        ),
        migrations.AddField(
            model_name="lineeventregistration",
            name="check_in",
            field=models.BooleanField(default=False, verbose_name="check-in"),
        ),
        migrations.AddField(
            model_name="personeventregistration",
            name="check_in",
            field=models.BooleanField(default=False, verbose_name="check-in"),
        ),
        migrations.AddField(
            model_name="scoutgroupeventregistration",
            name="check_in",
            field=models.BooleanField(default=False, verbose_name="check-in"),
        ),
        migrations.AddField(
            model_name="squadeventregistration",
            name="check_in",
            field=models.BooleanField(default=False, verbose_name="check-in"),
        ),
        migrations.AddField(
            model_name="subdistricteventregistration",
            name="check_in",
            field=models.BooleanField(default=False, verbose_name="check-in"),
        ),
    ]
