volumes:
  rn24-db: {}

services:
  db:
    image: postgis/postgis:16-3.4
    volumes:
      - rn24-db:/var/lib/postgresql/data
    env_file: .env
    restart: unless-stopped
  backend:
    build:
      context: .
    image: rn24/backend
    command: gunicorn -c gunicorn.conf.py
    volumes:
      - ./:/app
    depends_on:
      - db
    env_file: .env
    restart: unless-stopped
  frontend:
    build: https://github.com/Route-Nazionale-2024-AGESCI/rn24-app.git
    image: rn24/frontend
    volumes_from:
      - backend:rw
    restart: unless-stopped
    ports:
      - "127.0.0.1:8000:80"
