volumes:
  rn24-db: {}

services:
  db:
    image: postgis/postgis:16-3.4
    volumes:
      - rn24-db:/var/lib/postgresql/data
    env_file: .env
    restart: unless-stopped
  backend:
    build:
      context: .
    image: ghcr.io/route-nazionale-2024-agesci/rn24-backend:master
    command: gunicorn -c gunicorn.conf.py
    volumes:
      - ./:/app
    depends_on:
      - db
    env_file: .env
    restart: unless-stopped
  frontend:
    build: https://github.com/Route-Nazionale-2024-AGESCI/rn24-app.git
    image: ghcr.io/route-nazionale-2024-agesci/rn24-app:master
    volumes_from:
      - backend:rw
    restart: unless-stopped
    ports:
      - "127.0.0.1:8000:80"
  gotenberg:
    image: gotenberg/gotenberg:8
    command:
      - "gotenberg"
      - "--chromium-auto-start=true"
