# Generated by Django 5.0.4 on 2024-04-20 18:14

from django.db import migrations
from wagtail.models import Page, Locale, Site


def create_root_pages(apps, schema_editor):
    CMSPage = apps.get_model("cms.CMSPage")
    ContentType = apps.get_model("contenttypes.ContentType")

    # Get the content type for the Page model
    page_content_type = ContentType.objects.get(app_label="wagtailcore", model="page")

    root_page = Page.objects.order_by("id").first()
    # Page.objects.all().delete()
    # Site.objects.all().delete()

    default_locale = Locale.objects.first()

    home_page = CMSPage(
        title="RN24", body="", locale_id=default_locale.id, content_type=page_content_type
    )

    root_page.add_child(instance=home_page)

    # Refresh the home page instance, this Must be a PageInstance for the next step to work
    home_page = Page.objects.order_by("-id").first()
    home_page.add_child(
        instance=CMSPage(
            title="Eventi",
            body="eventi",
            locale_id=default_locale.id,
            content_type=page_content_type,
        )
    )

    # Create a site with the new homepage set as the root
    # Site.objects.create(hostname="localhost", root_page=home_page, is_default_site=True)
    site = Site.objects.get(is_default_site=True)
    site.root_page = home_page
    site.save()


class Migration(migrations.Migration):

    dependencies = [
        ("cms", "0002_alter_cmspage_options"),
    ]

    operations = [
        migrations.RunPython(create_root_pages, migrations.RunPython.noop),
    ]
