# Generated by Django 5.0.6 on 2024-07-10 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("settings", "0001_initial"),
    ]

    def create_setting(apps, schema_editor):
        Setting = apps.get_model("settings", "Setting")
        Setting._base_manager.get_or_create(key="BADGE_EXTRA_CSS")

    operations = [
        migrations.RunPython(create_setting),
    ]
