# Generated by Django 5.0.6 on 2024-07-10 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("settings", "0002_create_settings"),
    ]

    operations = [
        migrations.AlterField(
            model_name="setting",
            name="value",
            field=models.TextField(blank=True, null=True),
        ),
    ]
