# Generated by Django 5.0.3 on 2024-03-19 23:09

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("people", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="district",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, db_index=True, verbose_name="data di creazione"
            ),
        ),
        migrations.AlterField(
            model_name="district",
            name="deleted_at",
            field=models.DateTimeField(
                blank=True,
                db_index=True,
                editable=False,
                null=True,
                verbose_name="data di cancellazione",
            ),
        ),
        migrations.AlterField(
            model_name="district",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, db_index=True, verbose_name="data ultima modifica"
            ),
        ),
        migrations.AlterField(
            model_name="district",
            name="uuid",
            field=models.UUIDField(
                db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name="UUID"
            ),
        ),
        migrations.AlterField(
            model_name="person",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, db_index=True, verbose_name="data di creazione"
            ),
        ),
        migrations.AlterField(
            model_name="person",
            name="deleted_at",
            field=models.DateTimeField(
                blank=True,
                db_index=True,
                editable=False,
                null=True,
                verbose_name="data di cancellazione",
            ),
        ),
        migrations.AlterField(
            model_name="person",
            name="phone",
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name="telefono"),
        ),
        migrations.AlterField(
            model_name="person",
            name="scout_group",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="people.scoutgroup",
                verbose_name="gruppo scout",
            ),
        ),
        migrations.AlterField(
            model_name="person",
            name="squads",
            field=models.ManyToManyField(
                blank=True, related_name="members", to="people.squad", verbose_name="pattuglie"
            ),
        ),
        migrations.AlterField(
            model_name="person",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, db_index=True, verbose_name="data ultima modifica"
            ),
        ),
        migrations.AlterField(
            model_name="person",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="utente",
            ),
        ),
        migrations.AlterField(
            model_name="person",
            name="uuid",
            field=models.UUIDField(
                db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name="UUID"
            ),
        ),
        migrations.AlterField(
            model_name="scoutgroup",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, db_index=True, verbose_name="data di creazione"
            ),
        ),
        migrations.AlterField(
            model_name="scoutgroup",
            name="deleted_at",
            field=models.DateTimeField(
                blank=True,
                db_index=True,
                editable=False,
                null=True,
                verbose_name="data di cancellazione",
            ),
        ),
        migrations.AlterField(
            model_name="scoutgroup",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, db_index=True, verbose_name="data ultima modifica"
            ),
        ),
        migrations.AlterField(
            model_name="scoutgroup",
            name="uuid",
            field=models.UUIDField(
                db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name="UUID"
            ),
        ),
        migrations.AlterField(
            model_name="squad",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, db_index=True, verbose_name="data di creazione"
            ),
        ),
        migrations.AlterField(
            model_name="squad",
            name="deleted_at",
            field=models.DateTimeField(
                blank=True,
                db_index=True,
                editable=False,
                null=True,
                verbose_name="data di cancellazione",
            ),
        ),
        migrations.AlterField(
            model_name="squad",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, db_index=True, verbose_name="data ultima modifica"
            ),
        ),
        migrations.AlterField(
            model_name="squad",
            name="uuid",
            field=models.UUIDField(
                db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name="UUID"
            ),
        ),
        migrations.AlterField(
            model_name="subdistrict",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, db_index=True, verbose_name="data di creazione"
            ),
        ),
        migrations.AlterField(
            model_name="subdistrict",
            name="deleted_at",
            field=models.DateTimeField(
                blank=True,
                db_index=True,
                editable=False,
                null=True,
                verbose_name="data di cancellazione",
            ),
        ),
        migrations.AlterField(
            model_name="subdistrict",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, db_index=True, verbose_name="data ultima modifica"
            ),
        ),
        migrations.AlterField(
            model_name="subdistrict",
            name="uuid",
            field=models.UUIDField(
                db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name="UUID"
            ),
        ),
    ]
