# Generated by Django 5.0.3 on 2024-03-25 22:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("people", "0002_alter_district_created_at_alter_district_deleted_at_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="person",
            name="user",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
                verbose_name="utente",
            ),
        ),
        migrations.AlterField(
            model_name="scoutgroup",
            name="region",
            field=models.CharField(
                choices=[
                    ("ABRUZZO", "Abruzzo"),
                    ("BASILICATA", "Basilicata"),
                    ("CALABRIA", "Calabria"),
                    ("CAMPANIA", "Campania"),
                    ("EMILIA-ROMAGNA", "Emilia-Romagna"),
                    ("FRIULI-VENEZIA GIULIA", "Friuli-Venezia Giulia"),
                    ("LAZIO", "Lazio"),
                    ("LIGURIA", "Liguria"),
                    ("LOMBARDIA", "Lombardia"),
                    ("MARCHE", "Marche"),
                    ("MOLISE", "Molise"),
                    ("PIEMONTE", "Piemonte"),
                    ("PUGLIA", "Puglia"),
                    ("SARDEGNA", "Sardegna"),
                    ("SICILIA", "Sicilia"),
                    ("TOSCANA", "Toscana"),
                    ("TRENTINO-ALTO ADIGE", "Trentino-Alto Adige"),
                    ("UMBRIA", "Umbria"),
                    ("VALLE D'AOSTA", "Valle d'Aosta"),
                    ("VENETO", "Veneto"),
                ],
                max_length=255,
                verbose_name="regione",
            ),
        ),
    ]
