# Generated by Django 5.0.4 on 2024-04-20 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("people", "0003_alter_person_user_alter_scoutgroup_region"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="person",
            name="address",
        ),
        migrations.RemoveField(
            model_name="person",
            name="birth_date",
        ),
        migrations.RemoveField(
            model_name="person",
            name="city",
        ),
        migrations.RemoveField(
            model_name="person",
            name="codice_fiscale",
        ),
    ]
