# Generated by Django 5.0.4 on 2024-04-20 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("people", "0004_remove_person_address_remove_person_birth_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="scoutgroup",
            name="agesci_id",
            field=models.CharField(
                max_length=255, null=True, unique=True, verbose_name="codice AGESCI"
            ),
        ),
    ]
