# Generated by Django 5.0.4 on 2024-05-05 09:58

from django.db import migrations

from maps.factories import FuzzyPoint


def forwards_func(apps, schema_editor):
    Location = apps.get_model("maps", "Location")
    Subdistrict = apps.get_model("people", "Subdistrict")
    District = apps.get_model("people", "District")

    for subdistrict in Subdistrict._default_manager.all():
        if subdistrict.location:
            continue
        subdistrict.location = Location._default_manager.create(
            name=subdistrict.name,
            coords=FuzzyPoint().fuzz(),
        )
        subdistrict.save()

    for district in District._default_manager.all():
        if district.location:
            continue
        district.location = Location._default_manager.create(
            name=district.name,
            coords=FuzzyPoint().fuzz(),
        )
        district.save()


class Migration(migrations.Migration):

    dependencies = [
        ("people", "0006_district_location_subdistrict_location"),
    ]

    operations = [migrations.RunPython(forwards_func, reverse_code=migrations.RunPython.noop)]
