# Generated by Django 5.0.4 on 2024-05-05 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("people", "0009_person_arrived_at_person_is_arrived_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="person",
            name="is_arrived",
            field=models.BooleanField(db_index=True, default=False, verbose_name="arrivato?"),
        ),
        migrations.AlterField(
            model_name="scoutgroup",
            name="is_arrived",
            field=models.BooleanField(db_index=True, default=False, verbose_name="arrivato?"),
        ),
    ]
