# Generated by Django 5.0.4 on 2024-05-05 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("people", "0010_alter_person_is_arrived_alter_scoutgroup_is_arrived"),
    ]

    operations = [
        migrations.AddField(
            model_name="squad",
            name="groups",
            field=models.ManyToManyField(
                blank=True, related_name="squads", to="auth.group", verbose_name="gruppi"
            ),
        ),
    ]
