# Generated by Django 5.0.6 on 2024-05-12 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("people", "0012_alter_person_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="person",
            name="address",
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name="indirizzo"),
        ),
        migrations.AddField(
            model_name="person",
            name="birth_date",
            field=models.DateField(blank=True, null=True, verbose_name="data di nascita"),
        ),
        migrations.AddField(
            model_name="person",
            name="city",
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name="città"),
        ),
        migrations.AddField(
            model_name="person",
            name="gender",
            field=models.CharField(
                blank=True,
                choices=[("M", "Maschio"), ("F", "Femmina")],
                max_length=255,
                null=True,
                verbose_name="sesso",
            ),
        ),
        migrations.AddField(
            model_name="person",
            name="province",
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name="provincia"),
        ),
        migrations.AddField(
            model_name="person",
            name="region",
            field=models.CharField(
                blank=True,
                choices=[
                    ("ABRUZZO", "Abruzzo"),
                    ("BASILICATA", "Basilicata"),
                    ("CALABRIA", "Calabria"),
                    ("CAMPANIA", "Campania"),
                    ("EMILIA-ROMAGNA", "Emilia-Romagna"),
                    ("FRIULI-VENEZIA GIULIA", "Friuli-Venezia Giulia"),
                    ("LAZIO", "Lazio"),
                    ("LIGURIA", "Liguria"),
                    ("LOMBARDIA", "Lombardia"),
                    ("MARCHE", "Marche"),
                    ("MOLISE", "Molise"),
                    ("PIEMONTE", "Piemonte"),
                    ("PUGLIA", "Puglia"),
                    ("SARDEGNA", "Sardegna"),
                    ("SICILIA", "Sicilia"),
                    ("TOSCANA", "Toscana"),
                    ("TRENTINO-ALTO ADIGE", "Trentino-Alto Adige"),
                    ("UMBRIA", "Umbria"),
                    ("VALLE D'AOSTA", "Valle d'Aosta"),
                    ("VENETO", "Veneto"),
                ],
                max_length=255,
                null=True,
                verbose_name="regione",
            ),
        ),
        migrations.AddField(
            model_name="person",
            name="training_level",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="livello di formazione"
            ),
        ),
        migrations.AddField(
            model_name="person",
            name="zip_code",
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name="CAP"),
        ),
    ]
