# Generated by Django 5.0.6 on 2024-05-12 20:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("people", "0013_person_address_person_birth_date_person_city_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="scoutgroup",
            name="subdistrict",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="people.subdistrict",
                verbose_name="contrada",
            ),
        ),
    ]
