# Generated by Django 5.0.6 on 2024-05-14 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("people", "0014_alter_scoutgroup_subdistrict"),
    ]

    operations = [
        migrations.AlterField(
            model_name="person",
            name="email",
            field=models.EmailField(
                db_index=True,
                help_text="ricorda: purtroppo l'email non è univoca!",
                max_length=254,
                verbose_name="email",
            ),
        ),
    ]
