# Generated by Django 5.0.6 on 2024-05-26 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("people", "0015_alter_person_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="person",
            name="accessibility_has_caretaker_not_registered",
            field=models.BooleanField(
                default=False, verbose_name="viaggia con accompagnatore non iscritto?"
            ),
        ),
        migrations.AddField(
            model_name="person",
            name="accessibility_has_wheelchair",
            field=models.BooleanField(default=False, verbose_name="sedia a rotelle?"),
        ),
        migrations.AddField(
            model_name="person",
            name="food_allergies",
            field=models.TextField(
                blank=True,
                null=True,
                verbose_name="Selezionare una o più allergie/intolleranze elencate:",
            ),
        ),
        migrations.AddField(
            model_name="person",
            name="food_diet_needed",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Nessuna", "Nessuna"),
                    (
                        "Monodieta (selezionare nel caso di singola allergia/intolleranza)",
                        "Monodieta (selezionare nel caso di singola allergia/intolleranza)",
                    ),
                    (
                        "Multidieta (selezionare nel caso di più allergie/intolleranze)",
                        "Multidieta (selezionare nel caso di più allergie/intolleranze)",
                    ),
                    (
                        "Dieta da shock (selezionare nel caso di una o più allergie che possano causare shock anafilattico)",
                        "Dieta da shock (selezionare nel caso di una o più allergie che possano causare shock anafilattico)",
                    ),
                ],
                max_length=255,
                null=True,
                verbose_name="Allergie/intolleranze ad alimenti da segnalare.",
            ),
        ),
        migrations.AddField(
            model_name="person",
            name="food_is_vegan",
            field=models.BooleanField(default=False, verbose_name="Segui una dieta vegana?"),
        ),
        migrations.AddField(
            model_name="person",
            name="health_allergies",
            field=models.TextField(blank=True, null=True, verbose_name="allergie"),
        ),
        migrations.AddField(
            model_name="person",
            name="health_has_allergies",
            field=models.BooleanField(default=False, verbose_name="Hai allergie accertate?"),
        ),
        migrations.AddField(
            model_name="person",
            name="health_has_movement_disorders",
            field=models.BooleanField(
                default=False, verbose_name="Sei affetto da disturbi motori?"
            ),
        ),
        migrations.AddField(
            model_name="person",
            name="health_has_patologies",
            field=models.BooleanField(
                default=False,
                verbose_name="Sei affetto da patologie cardiovascolari/respiratorie/neurologiche?",
            ),
        ),
        migrations.AddField(
            model_name="person",
            name="health_movement_disorders",
            field=models.TextField(blank=True, null=True, verbose_name="disturbi motori"),
        ),
        migrations.AddField(
            model_name="person",
            name="health_patologies",
            field=models.TextField(blank=True, null=True, verbose_name="patologie accertate"),
        ),
        migrations.AddField(
            model_name="person",
            name="sleeping_is_sleeping_in_tent",
            field=models.BooleanField(default=False, verbose_name="dorme in tenda personale?"),
        ),
        migrations.AddField(
            model_name="person",
            name="sleeping_place",
            field=models.TextField(
                blank=True,
                null=True,
                verbose_name="Per motivi di disabilità/patologie ho bisogno di dormire:",
            ),
        ),
        migrations.AddField(
            model_name="person",
            name="sleeping_requests",
            field=models.TextField(blank=True, null=True, verbose_name="richieste per il pernotto"),
        ),
        migrations.AddField(
            model_name="person",
            name="sleeping_requests_2",
            field=models.TextField(
                blank=True, null=True, verbose_name="richieste per il pernotto (2)"
            ),
        ),
        migrations.AddField(
            model_name="person",
            name="transportation_has_problems_moving_on_foot",
            field=models.BooleanField(
                default=False,
                verbose_name="Hai disabilità/patologie/età che non ti permettono di sostenere gli spostamenti a piedi previsti?",
            ),
        ),
        migrations.AddField(
            model_name="person",
            name="transportation_need_transport",
            field=models.BooleanField(
                default=False,
                verbose_name="Necessiti di un accompagnatore fornito dall'organizzazione durante l'evento?",
            ),
        ),
    ]
