# Generated by Django 5.0.6 on 2024-05-30 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("people", "0015_alter_person_email"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="person",
            options={
                "permissions": (
                    ("is_staff", "Può accedere al backoffice"),
                    ("can_scan_qr", "Può scansionare i badge"),
                ),
                "verbose_name": "persona",
                "verbose_name_plural": "persone",
            },
        ),
    ]
