# Generated by Django 5.0.6 on 2024-06-05 17:41

import django.db.models.deletion
import django.db.models.manager
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("maps", "0003_alter_location_name"),
        ("people", "0016_alter_person_options"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="scoutgroup",
            name="subdistrict",
        ),
        migrations.CreateModel(
            name="Line",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="data di creazione"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, db_index=True, verbose_name="data ultima modifica"
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        unique=True,
                        verbose_name="UUID",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        editable=False,
                        null=True,
                        verbose_name="data di cancellazione",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True, verbose_name="nome")),
                (
                    "location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="maps.location",
                        verbose_name="luogo",
                    ),
                ),
                (
                    "subdistrict",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="people.subdistrict",
                        verbose_name="contrada",
                    ),
                ),
            ],
            options={
                "verbose_name": "fila",
                "verbose_name_plural": "file",
            },
            managers=[
                ("objects_with_deleted", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name="scoutgroup",
            name="line",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="people.line",
                verbose_name="fila",
            ),
        ),
    ]
