# Generated by Django 5.0.6 on 2024-06-05 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("people", "0017_remove_scoutgroup_subdistrict_line_scoutgroup_line"),
    ]

    operations = [
        migrations.AlterField(
            model_name="line",
            name="name",
            field=models.CharField(max_length=255, verbose_name="nome"),
        ),
        migrations.AlterField(
            model_name="subdistrict",
            name="name",
            field=models.CharField(max_length=255, verbose_name="nome"),
        ),
    ]
