# Generated by Django 5.0.6 on 2024-06-20 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("people", "0018_alter_line_name_alter_subdistrict_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="person",
            name="agesci_id",
            field=models.CharField(
                blank=True,
                db_index=True,
                max_length=255,
                null=True,
                unique=True,
                verbose_name="codice AGESCI",
            ),
        ),
    ]
