# Generated by Django 5.0.6 on 2024-07-05 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("people", "0021_add_all_person_personal_data"),
    ]

    operations = [
        migrations.AlterField(
            model_name="person",
            name="region",
            field=models.CharField(
                blank=True,
                choices=[
                    ("ABRUZZO", "Abruzzo"),
                    ("BASILICATA", "Basilicata"),
                    ("CALABRIA", "Calabria"),
                    ("CAMPANIA", "Campania"),
                    ("EMILIA ROMAGNA", "Emilia-Romagna"),
                    ("FRIULI VENEZIA GIULIA", "Friuli-Venezia Giulia"),
                    ("LAZIO", "Lazio"),
                    ("LIGURIA", "Liguria"),
                    ("LOMBARDIA", "Lombardia"),
                    ("MARCHE", "Marche"),
                    ("MOLISE", "Molise"),
                    ("PIEMONTE", "Piemonte"),
                    ("PUGLIA", "Puglia"),
                    ("SARDEGNA", "Sardegna"),
                    ("SICILIA", "Sicilia"),
                    ("TOSCANA", "Toscana"),
                    ("TRENTINO ALTO ADIGE", "Trentino-Alto Adige"),
                    ("UMBRIA", "Umbria"),
                    ("VALLE D'AOSTA", "Valle d'Aosta"),
                    ("VENETO", "Veneto"),
                ],
                max_length=255,
                null=True,
                verbose_name="regione",
            ),
        ),
        migrations.AlterField(
            model_name="person",
            name="transportation_need_transport",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="Necessiti di un accompagnatore fornito dall'organizzazione durante l'evento?",
            ),
        ),
        migrations.AlterField(
            model_name="scoutgroup",
            name="region",
            field=models.CharField(
                choices=[
                    ("ABRUZZO", "Abruzzo"),
                    ("BASILICATA", "Basilicata"),
                    ("CALABRIA", "Calabria"),
                    ("CAMPANIA", "Campania"),
                    ("EMILIA ROMAGNA", "Emilia-Romagna"),
                    ("FRIULI VENEZIA GIULIA", "Friuli-Venezia Giulia"),
                    ("LAZIO", "Lazio"),
                    ("LIGURIA", "Liguria"),
                    ("LOMBARDIA", "Lombardia"),
                    ("MARCHE", "Marche"),
                    ("MOLISE", "Molise"),
                    ("PIEMONTE", "Piemonte"),
                    ("PUGLIA", "Puglia"),
                    ("SARDEGNA", "Sardegna"),
                    ("SICILIA", "Sicilia"),
                    ("TOSCANA", "Toscana"),
                    ("TRENTINO ALTO ADIGE", "Trentino-Alto Adige"),
                    ("UMBRIA", "Umbria"),
                    ("VALLE D'AOSTA", "Valle d'Aosta"),
                    ("VENETO", "Veneto"),
                ],
                max_length=255,
                verbose_name="regione",
            ),
        ),
    ]
