# Generated by Django 5.0.6 on 2024-07-16 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("people", "0024_person_notes"),
    ]

    operations = [
        migrations.DeleteModel(
            name="SensibleData",
        ),
        migrations.AlterField(
            model_name="person",
            name="accessibility_has_caretaker_not_registered",
            field=models.BooleanField(
                default=False,
                help_text="viaggia con accompagnatore non iscritto?",
                verbose_name="accompagnatore?",
            ),
        ),
        migrations.AlterField(
            model_name="person",
            name="food_diet_needed",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Nessuna", "Nessuna"),
                    (
                        "Monodieta (selezionare nel caso di singola allergia/intolleranza)",
                        "Monodieta (selezionare nel caso di singola allergia/intolleranza)",
                    ),
                    (
                        "Multidieta (selezionare nel caso di più allergie/intolleranze)",
                        "Multidieta (selezionare nel caso di più allergie/intolleranze)",
                    ),
                    (
                        "Dieta da shock (selezionare nel caso di una o più allergie che possano causare shock anafilattico)",
                        "Dieta da shock (selezionare nel caso di una o più allergie che possano causare shock anafilattico)",
                    ),
                ],
                help_text="Allergie/intolleranze ad alimenti da segnalare.",
                max_length=255,
                null=True,
                verbose_name="dieta",
            ),
        ),
        migrations.AlterField(
            model_name="person",
            name="food_is_vegan",
            field=models.BooleanField(
                default=False, help_text="Segui una dieta vegana?", verbose_name="vegano?"
            ),
        ),
        migrations.AlterField(
            model_name="person",
            name="health_has_allergies",
            field=models.BooleanField(
                default=False, help_text="Hai allergie accertate?", verbose_name="allergie?"
            ),
        ),
        migrations.AlterField(
            model_name="person",
            name="health_has_movement_disorders",
            field=models.BooleanField(
                default=False,
                help_text="Sei affetto da disturbi motori?",
                verbose_name="disturbi motori?",
            ),
        ),
        migrations.AlterField(
            model_name="person",
            name="health_has_patologies",
            field=models.BooleanField(
                default=False,
                help_text="Sei affetto da patologie cardiovascolari/respiratorie/neurologiche?",
                verbose_name="patologie?",
            ),
        ),
        migrations.AlterField(
            model_name="person",
            name="sleeping_is_sleeping_in_tent",
            field=models.BooleanField(
                default=False, help_text="dorme in tenda personale?", verbose_name="tenda?"
            ),
        ),
        migrations.AlterField(
            model_name="person",
            name="transportation_has_problems_moving_on_foot",
            field=models.BooleanField(
                default=False,
                help_text="Hai disabilità/patologie/età che non ti permettono di sostenere gli spostamenti a piedi previsti?",
                verbose_name="spostamento a piedi?",
            ),
        ),
    ]
