# Generated by Django 5.0.6 on 2024-07-17 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("people", "0027_alter_personcheckin_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="scoutgroup",
            name="name",
            field=models.CharField(db_index=True, max_length=255, unique=True, verbose_name="nome"),
        ),
        migrations.AlterField(
            model_name="squad",
            name="name",
            field=models.CharField(db_index=True, max_length=255, unique=True, verbose_name="nome"),
        ),
    ]
