# Generated by Django 5.0.6 on 2024-07-18 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("people", "0028_alter_scoutgroup_name_alter_squad_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="person",
            name="food_diet_needed",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Allergie/intolleranze ad alimenti da segnalare.",
                max_length=255,
                null=True,
                verbose_name="dieta",
            ),
        ),
    ]
