# Generated by Django 5.0.6 on 2024-07-18 23:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cms", "0003_create_root_pages"),
        ("people", "0032_squad_page"),
    ]

    operations = [
        migrations.AlterField(
            model_name="squad",
            name="page",
            field=models.ForeignKey(
                blank=True,
                help_text="la pagina CMS viene creata automaticamente al salvataggio",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="cms.cmspage",
                verbose_name="pagina",
            ),
        ),
    ]
