# Generated by Django 5.0.6 on 2024-07-18 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("people", "0033_alter_squad_page"),
    ]

    operations = [
        migrations.AddField(
            model_name="person",
            name="is_available_for_extra_service",
            field=models.BooleanField(
                db_index=True, default=False, verbose_name="disponibile per servizio extra?"
            ),
        ),
    ]
