# Generated by Django 5.1 on 2024-08-12 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("people", "0034_person_is_available_for_extra_service"),
    ]

    operations = [
        migrations.AddField(
            model_name="scoutgroup",
            name="has_problems_with_payments",
            field=models.BooleanField(default=False, verbose_name="problemi pagamento?"),
        ),
        migrations.AddField(
            model_name="scoutgroup",
            name="notes",
            field=models.TextField(blank=True, null=True, verbose_name="note"),
        ),
        migrations.AddField(
            model_name="scoutgroup",
            name="problems_with_payments",
            field=models.TextField(blank=True, null=True, verbose_name="problemi pagamento"),
        ),
    ]
