# Generated by Django 5.1 on 2024-08-12 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("people", "0035_scoutgroup_has_problems_with_payments_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="scoutgroup",
            name="agesci_id",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="codice AGESCI"
            ),
        ),
    ]
