# Generated by Django 5.1 on 2024-08-14 17:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("maps", "0008_alter_location_coords"),
        ("people", "0036_alter_scoutgroup_agesci_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="district",
            name="location",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="maps.location",
                verbose_name="luogo",
            ),
        ),
        migrations.AlterField(
            model_name="subdistrict",
            name="location",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="maps.location",
                verbose_name="luogo",
            ),
        ),
    ]
