# Generated by Django 5.1 on 2024-08-17 10:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("maps", "0009_location_district"),
        ("people", "0037_alter_district_location_alter_subdistrict_location"),
    ]

    operations = [
        migrations.AlterField(
            model_name="district",
            name="location",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="districts",
                to="maps.location",
                verbose_name="luogo",
            ),
        ),
    ]
