# Generated by Django 5.1 on 2024-08-20 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("people", "0039_scoutgroup_arrival_date_scoutgroup_departure_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="person",
            name="sleeping_tent_name",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="tendone assegnato"
            ),
        ),
    ]
