# Generated by Django 5.1 on 2024-08-22 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("people", "0040_person_sleeping_tent_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="line",
            name="square_meters",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True, verbose_name="metri quadri"
            ),
        ),
        migrations.AddField(
            model_name="line",
            name="tent_slots",
            field=models.PositiveSmallIntegerField(
                blank=True, null=True, verbose_name="posti tenda"
            ),
        ),
    ]
